package com.toddler.footsteps

enum class Screens {
    NO_SCREEN,
    MAIN_SCREEN,
    CHART_SCREEN,
    STATISTICS_SCREEN,
    SETTINGS_SCREEN,
    DISCOVER_DEVICES_SCREEN,
    CONNECTED_DEVICES_SCREEN,
    PROFILE_SCREEN
}